[#93]방문한 팝업만 리뷰 작성
team4-SpotOn/spoton-backend pull request #99
Opened 2024-12-09 10:59 UTC by 11ioo

2024-12-09 11:02 UTC, inzulmi132 commented
새로 푸시하기 전까지 머지 금지

2024-12-09 11:15 UTC, 11ioo commented
확인하실때 포인트컨트롤러는 무시하셔도 됩니다!

2024-12-09 11:49 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java
> +    POPUPSTORE_NOT_FOUND(HttpStatus.BAD_REQUEST,"해당 팝업스토어가 없습니다."),
```suggestion
    POPUPSTORE_NOT_FOUND(HttpStatus.NOT_FOUND,"해당 팝업스토어가 없습니다."),
```
BAD_REQUEST를 사용한 이유가 없다면 NOT_FOUND로 해주세요.

2024-12-09 11:49 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java
> +    REVIEW_DOT_DELETE(HttpStatus.BAD_REQUEST,"댓글을 삭제할수 없습니다."),
```suggestion
    REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND,"수정할 리뷰가 없습니다."),
    REVIEW_NOT_UPDATE(HttpStatus.FORBIDDEN,"작성자만 수정할 수 있습니다."),
    REVIEW_ALREADY_DELETED(HttpStatus.NOT_FOUND,"이미 삭제된 리뷰입니다."),
    REVIEW_DOT_DELETE(HttpStatus.BAD_REQUEST,"댓글을 삭제할 수 없습니다."),
```

2024-12-09 11:49 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/dto/response/ReviewCreateResponseDto.java
> +import java.time.LocalDate;
```suggestion
```
옵티마이저 해주세요.

2024-12-09 11:49 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/dto/response/ReviewUpdateResponseDto.java
> +import java.time.LocalDate;
```suggestion
```
여기도요.

2024-12-09 11:49 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/entity/Review.java
> +import java.time.LocalDate;
```suggestion
```
옵티마이저

2024-12-09 11:49 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/service/ReviewService.java
> +        }
```suggestion
        if (!reservationRepository.existsByUserAndPopupStore(user, popupStore)) {
            throw new CustomException("예약한 팝업스토어가 아닙니다.");
        }
```
CustomException을 사용해주세요.

2024-12-09 11:49 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/service/ReviewService.java
> +            throw new CustomApiException(ErrorCode.REVIEW_DOT_DELETE);
DOT...?

2024-12-09 11:49 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/service/ReviewService.java
> +            throw new CustomApiException(ErrorCode.REVIEW_NOT_UPDATE);
뭔가 리뷰 작성자가 아니다, 권한이 없다 같은 이름으로 하면 어떨까 합니다.
그러면 delete 에서 같은 코드를 쓸 수 있을 거 같고요.

2024-12-09 12:04 UTC, inzulmi132 requested changes
[#81]이 머지되었으니 dev를 머지 혹은 리베이스 하시기 바랍니다.

2024-12-10 01:20 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/entity/Review.java
> +    public Review(Long id, PopupStore popupStore, User user, String contents, int star, String imageUrl, LocalDateTime createdAt, LocalDateTime updatedAt) {
```suggestion
    public Review(Long id, PopupStore popupStore, User user, String contents, int star, String imageUrl) {
```
생성일과 수정일은 jpa Auditing이 자동으로 넣어주는 값입니다.

2024-12-10 01:20 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/entity/Review.java
> +        this.updatedAt = updatedAt;
```suggestion
```

2024-12-10 01:20 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/entity/Review.java
> +    private LocalDateTime updatedAt;
```suggestion
```
baseEntity에서 상속 받는 필드입니다.

2024-12-10 01:20 UTC, inzulmi132 commented on src/main/java/com/sparta/popupstore/domain/review/service/ReviewService.java
> +            throw new CustomApiException(ErrorCode.REVIEW_DONT_DELETE);
dont 보다는 cant 같은 단어가 맞지 않나 싶습니다.

그리고 작성자가 아니다, 혹은 권한이 없다는 에러 코드로 한다면 update와 delete에서 모두 쓸 수 있을 것 같습니다.

2024-12-10 01:31 UTC, inzulmi132 approved these changes

2024-12-10 01:31 UTC, merged